# Font configuration
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# Window layout
window_padding_width 10
background_opacity 0.8

# Cursor
cursor_shape beam

# Scrollback
scrollback_lines 5000

# Performance
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Terminal Bell
enable_audio_bell no


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME