;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;==========================================================

[colors]
; Using Atom OneDark colour scheme.
background = #D0111111
background-alt = #1D405C
foreground = #C5C8C6
primary = #61AFEF          
secondary = #C678DD
tertiary = #90b061
alert = #A54242
disabled = #707880

[bar/main]
width = 100%
height = 32pt
radius = 14

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

# Fallback monitor if not set via environment variable
monitor = ${env:MONITOR:DisplayPort-1}

# Invisible border.
border-color = #00000000

;==========================================================
;                         Modules
;==========================================================
modules-left = xworkspaces twilight brightness 
modules-center = date 
modules-right = speaker-volume pdt-date nyc-date wlan eth 

;==========================================================
;                         Spacing
;==========================================================
# Margin.
border-left-size = 14pt
border-right-size = 14pt
border-top-size = 6pt
border-bottom-size = 6pt

# Padding.
padding-left = 32pt 
padding-right = 32pt

# Separation.
module-margin = 10pt

separator = /
separator-foreground = ${colors.disabled}

# Fonts are defined using <font-name>;<vertical-offset>
font-0 = "Ubuntu Mono:size=14;3"
font-1 = Font Awesome 6 Free:pixelsize=14;3
font-2 = Font Awesome 6 Free Solid:pixelsize=14;3
font-3 = Font Awesome 6 Brands:pixelsize=14;3
font-4 = "MesloLGS NF:size=14;3"
font-5 = "Symbola:pixelsize=14;3"

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 2

label-occupied = %name%
label-occupied-padding = 2

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 2

[module/pulseaudio-control-output]
type = custom/script
tail = true
label-foreground = ${colors.primary}
exec = pulseaudio-control --icons-volume ", " --icon-muted "(Muted) " --node-nicknames-from "device.description" listen
click-right = exec pavucontrol &
click-left = pulseaudio-control togmute
scroll-up = pulseaudio-control --volume-max 130 up
scroll-down = pulseaudio-control --volume-max 130 down

[module/pulseaudio-control-output-name-only]
type = custom/script
tail = true
label-foreground = ${colors.primary}
exec = pulseaudio-control --node-nicknames-from "device.description" --format ' $NODE_NICKNAME' listen
click-right = exec pavucontrol &
click-left = pulseaudio-control togmute
scroll-up = pulseaudio-control --volume-max 130 up
scroll-down = pulseaudio-control --volume-max 130 down

[module/pulseaudio-control-input]
type = custom/script
tail = true
label-foreground = ${colors.primary}
exec = pulseaudio-control  --node-type input --icons-volume "" --icon-muted "(Muted) " --node-nicknames-from "device.description" listen
click-right = exec pavucontrol &
click-left = pulseaudio-control --node-type input togmute
click-middle = pulseaudio-control --node-type input next-node
scroll-up = pulseaudio-control --node-type input --volume-max 130 up
scroll-down = pulseaudio-control --node-type input --volume-max 130 down

[module/pulseaudio-control-input-name-only]
type = custom/script
tail = true
label-foreground = ${colors.primary}
exec = pulseaudio-control  --node-type input --node-nicknames-from "device.description" --format ' $NODE_NICKNAME' listen
click-right = exec pavucontrol &
click-left = pulseaudio-control --node-type input togmute
click-middle = pulseaudio-control --node-type input next-node
scroll-up = pulseaudio-control --node-type input --volume-max 130 up
scroll-down = pulseaudio-control --node-type input --volume-max 130 down

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = "WiFi %{F#90B061}(%essid%) ✓%{F-}"
label-disconnected = ""

[module/eth]
inherit = network-base
interface-type = wired
label-foreground = ${colors.primary}
label-connected = %{F#90B061}Ethernet ✓%{F-}
label-disconnected = ""

[module/twilight]
type = custom/script
label-foreground = ${colors.alert}
exec = echo 🌡️
scroll-down = redshift -O 5000
scroll-up = redshift -x

[module/brightness]
type = custom/script
label-foreground = ${colors.tertiary}
exec = echo ☀️
scroll-down = redshift -O 6500 -b 0.9
scroll-up = redshift -x

[module/date]
type = custom/script
interval = 1
exec = date '+%b %d | %I:%M %p'
scroll-up = date
label-foreground = ${colors.primary}

[module/cava]
type = custom/script
tail = true
exec = $HOME/.config/polybar/cava.sh
format = <label>
format-font = 5
label = %output%

[module/i3-volume]
type = custom/script
tail = true
label = %output%
exec = ~/i3-volume/volume listen "%i %v %p\\n"
scroll-up = ~/i3-volume/volume up
scroll-down = ~/i3-volume/volume down
click-left = ~/i3-volume/volume mute
click-right = exec pavucontrol &

[module/nyc-date]
type = custom/script
interval = 1
exec = echo "NYC $(TZ='America/New_York' date '+%I:%M %p')"
scroll-up = date

[module/pdt-date]
type = custom/script
interval = 1
exec = echo "PDT $(TZ='America/Los_Angeles' date '+%I:%M %p')"
scroll-up = date

[module/speaker-volume]
type = custom/script
tail = true
label-foreground = ${colors.primary}
exec = echo "Vol: $(amixer get Master | grep -Po '\d+%' | head -n 1)"

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
