preload = /home/tym/Pictures/Wallpapers/cityscape/tokyo-night.jpg
wallpaper = DP-1,/home/tym/Pictures/Wallpapers/cityscape/tokyo-night.jpg
wallpaper = DP-2,/home/tym/Pictures/Wallpapers/cityscape/tokyo-night.jpg
splash = false
